SCREEN_TITLE_MAIN = "Mischa's FileInspector:   "
SCREEN_TITLE_FIND_DUPLICATES = SCREEN_TITLE_MAIN + "Find duplicates"
SCREEN_TITLE_FILENAME_CHANGE = SCREEN_TITLE_MAIN + "Filename/s change"
SCREEN_TITLE_INFO = SCREEN_TITLE_MAIN + "Info"
SCREEN_TITLE_CONFIGURATION = SCREEN_TITLE_MAIN + "Configuration"

# End-of-file (EOF)
